name: griddy
description: Actual screen sizes of smartphones on a desktop monitor.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluent_ui: ^3.9.1
  desktop_window: ^0.4.0
  html: ^0.15.0
  http: ^0.13.4
  provider: ^6.0.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - images/

